# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=znver2 -mtune=znver2 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
LDFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# USE flags
USE="avahi clang pulseaudio dbus fcitx4 elogind ipv6 libsamplerate qt5 \
     kde samba X zeroconf -accessiblity -geolocation -systemd -gnome \
     -ibm -webengine -telepathy -ieee1394"

# Install latest package versions
ACCEPT_KEYWORDS="~amd64"

# Hardware specifics
VIDEO_CARDS="nvidia"

# Language targets
PYTHON_TARGETS="python3_9 python3_8"
PYTHON_SINGLE_TARGET="python3_8"

EMERGE_DEFAULT_OPTS="-a --jobs 3 ${EMERGE_DEFAULT_OPTS}"
MAKEOPTS="-j12"

# Accept soyvidia license
ACCEPT_LICENSE="@EULA"

# Only build English support
L10N="en-GB en-AU"

# QEMU stuff
QEMU_USER_TARGETS="x86_64"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C

GENTOO_MIRRORS="https://mirror.aarnet.edu.au/pub/gentoo/"
GRUB_PLATFORMS="efi-64"
